# Generated by Django 4.1.1 on 2023-12-02 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100, unique=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('doctorQualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'DoctorTable',
            },
        ),
    ]
