# Generated by Django 4.1.1 on 2023-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctorregistrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockChainTransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_index', models.CharField(max_length=100)),
                ('c_timestamp', models.CharField(max_length=100)),
                ('c_sender', models.CharField(max_length=100)),
                ('c_recipient', models.CharField(max_length=100)),
                ('c_vote', models.CharField(max_length=100)),
                ('c_proof', models.CharField(max_length=100)),
                ('c_previous_hash', models.CharField(max_length=100)),
                ('p_index', models.CharField(max_length=100)),
                ('p_timestamp', models.CharField(max_length=100)),
                ('p_sender', models.CharField(max_length=100)),
                ('p_recipient', models.CharField(max_length=100)),
                ('p_vote', models.CharField(max_length=100)),
                ('p_proof', models.CharField(max_length=100)),
                ('p_previous_hash', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BlockChainTransactiontable',
            },
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginid', models.CharField(max_length=100)),
                ('patientName', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('doctor', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('patientEmail', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('fileName', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/')),
                ('cdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PatientTable',
            },
        ),
    ]
